#+TITLE: Kill Vanity Phone
#+AUTHOR: Andrew Jarrett

A dead simple node module that listens on the command line for a vanity phone number (e.g. "(855) CALL-NOW" or "BEERS4BRETT") and copies the conversion to the system clipboard.

* kill-vanity-phone

I created this for work, where I often have to convert phone numbers on the fly to look them up in our database.

- listens continuously for better workflow (using readline.createInterface)

- strips non-numeric / non-alphabetic characters

- strips extra characters (to deal with vanity numbers that add letters for semantic meaning)

- uses =copy-paste= to work with native system clipboard (works on OS X, Windows, Linux and OpenBSD)

- super thin; only dependency is [[https://www.npmjs.com/package/copy-paste][node-copy-paste]] (and obviously [[https://nodejs.org][Node.js]])

*** Note:

Only supports countries with 10-digit phone numbers, as it strips anything longer and will treat superfluous characters as part of the output for countries with shorter phone numbers.

This can easily be changed by editing index.js to change the second argument to =substr=, in this case =10=.

*** License

Distributed with the MIT License

*** Contributing

Feel free to open an issue/PR if you find a bug or want to support a feature that you think should be added!

